#!/usr/bin/env python
from serial.tools.miniterm import main
from cloudmanager_micropython_esp8266 import determine_default_serial_port


if __name__ == '__main__':
    main(default_port=determine_default_serial_port(), default_baudrate=115200)

